In [1]:
print('nurc-tts')

nurc-tts

In [2]:
import pandas as pd

# Carrega o arquivo CSV
df = pd.read_csv('nurc_tts_SELECIONADOS.csv')

# Exibe as 5 primeiras linhas para verificar se deu certo
df.head()

,inquiry,segment,speaker,start_time,end_time,duration,text,inq_type,inq_recording_year,inq_gender,inq_age_group,inq_quality,inq_themes
0,NURC_RE_DID_001,NURC_RE_DID_001_Inf-ue_937_2148.897_2155.569.wav,Inf-ue,2148.897,2155.569,6.671,mas normalmente eu acho muito perigoso princip...,DID,1974,M,II,Ótima,"Transportes, Viagens"
1,NURC_RE_DID_001,NURC_RE_DID_001_Inf-ue_151_102.667_108.248.wav,Inf-ue,102.667,108.248,5.582,e posteriormente fui conduzido para a escola A...,DID,1974,M,II,Ótima,"Transportes, Viagens"
2,NURC_RE_DID_001,NURC_RE_DID_001_Inf-ue_558_1149.132_1154.554.wav,Inf-ue,1149.132,1154.554,5.423,em primeiro lugar eu faria uma viagem à Europa...,DID,1974,M,II,Ótima,"Transportes, Viagens"
3,NURC_RE_DID_001,NURC_RE_DID_001_Inf-ue_420_832.051_836.831.wav,Inf-ue,832.051,836.831,4.780,mas nem todo conforto advém do progresso pelo ...,DID,1974,M,II,Ótima,"Transportes, Viagens"
4,NURC_RE_DID_001,NURC_RE_DID_001_Inf-ue_200_243.659_247.495.wav,Inf-ue,243.659,247.495,3.836,no lugar de ser um oficial de marinha me torne...,DID,1974,M,II,Ótima,"Transportes, Viagens"

In [4]:
import re
alphabet = r"ABCDEFGHIJKLMNOPQRSTUVWXYZÇÃÀÁÂÊÉÍÓÔÕÚÛabcdefghijklmnopqrstuvwxyzçãàáâêéíóôõũúû1234567890%\-\n/\\ "

def replace_special_tokens_and_normalize(text):
    text = text.lower()

    map_words = {
        "éh": "eh",
        "ehm": "eh",
        "ehn": "eh",
        "hum": "uh",
        "hm": "uh",
        "uhm": "uh",
        "hã": "ah",
        "ãh": "ah",
        "ã":  "ah",
        "hmm": "uh",
        "mm": "uh",
        "mhm": "uh"
    }

    text = re.sub("h+", "h", text)
    text = re.sub("[^{}]".format(alphabet+" "), " ", text)
    text = re.sub("[ ]+", " ", text)

    words = text.split(' ')
    new_words = []
    for word in words:
        if word == '' or word == ' ':
            continue
        if word in map_words:
            new_words.append(map_words[word])
        else:
            new_words.append(word)

    return " ".join(new_words)

In [5]:
# Aplica a função na coluna 'text' e salva o resultado nela mesma
df['text'] = df['text'].apply(replace_special_tokens_and_normalize)

df.head()

,inquiry,segment,speaker,start_time,end_time,duration,text,inq_type,inq_recording_year,inq_gender,inq_age_group,inq_quality,inq_themes
0,NURC_RE_DID_001,NURC_RE_DID_001_Inf-ue_937_2148.897_2155.569.wav,Inf-ue,2148.897,2155.569,6.671,mas normalmente eu acho muito perigoso princip...,DID,1974,M,II,Ótima,"Transportes, Viagens"
1,NURC_RE_DID_001,NURC_RE_DID_001_Inf-ue_151_102.667_108.248.wav,Inf-ue,102.667,108.248,5.582,e posteriormente fui conduzido para a escola a...,DID,1974,M,II,Ótima,"Transportes, Viagens"
2,NURC_RE_DID_001,NURC_RE_DID_001_Inf-ue_558_1149.132_1154.554.wav,Inf-ue,1149.132,1154.554,5.423,em primeiro lugar eu faria uma viagem à europa...,DID,1974,M,II,Ótima,"Transportes, Viagens"
3,NURC_RE_DID_001,NURC_RE_DID_001_Inf-ue_420_832.051_836.831.wav,Inf-ue,832.051,836.831,4.780,mas nem todo conforto advém do progresso pelo ...,DID,1974,M,II,Ótima,"Transportes, Viagens"
4,NURC_RE_DID_001,NURC_RE_DID_001_Inf-ue_200_243.659_247.495.wav,Inf-ue,243.659,247.495,3.836,no lugar de ser um oficial de marinha me torne...,DID,1974,M,II,Ótima,"Transportes, Viagens"

In [6]:
# Salva o DataFrame em um novo arquivo CSV
df.to_csv('nurc_tts_SELECIONADOS_normalizado.csv', index=False, encoding='utf-8')