In [2]:
print('nurc-tts')

nurc-tts

In [ ]:
!pip install datasets

In [5]:
from datasets import load_dataset
import pandas as pd

In [ ]:
ds = load_dataset('sidleal/nurc_tts_24khz')
print(ds)

In [23]:
splits = ['sao_paulo', 'recife']
all_metadata = []

for split_name in splits:
    ds = load_dataset('sidleal/nurc_tts_24khz', split=split_name)
    metadata = ds.remove_columns(['audio'])
    for entry in metadata:
        entry['split'] = split_name
        all_metadata.append(entry)

df = pd.DataFrame(all_metadata)

print(f"Total metadata rows loaded: {len(df)}")
display(df.head())

Resolving data files:   0%|          | 0/68 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/113 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/68 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/113 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/78 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/68 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/113 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/68 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/113 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/111 [00:00<?, ?it/s]

Total metadata rows loaded: 320916

,inquiry,segment,speaker,duration,text,inq_type,inq_recording_year,inq_gender,inq_quality,inq_themes,inq_age_group,split
0,SP_D2_015,SP_D2_015_SPEAKER_1_3_539.293_544.071.wav,SPEAKER 1,4.778,e cinco litros. o alqueire de são paulo? qual ...,D2,1971,M e M,Ótima,"Vegetais, agricultura Animais, rebanho",II e II,sao_paulo
1,SP_D2_015,SP_D2_015_SPEAKER_1_5_898.716_903.438.wav,SPEAKER 1,4.722,"muito bom. quais são as fases, todas as fases ...",D2,1971,M e M,Ótima,"Vegetais, agricultura Animais, rebanho",II e II,sao_paulo
2,SP_D2_015,SP_D2_015_SPEAKER_1_7_2346.528_2351.128.wav,SPEAKER 1,4.600,como é que ele cuida do umbigo do piseiro?,D2,1971,M e M,Ótima,"Vegetais, agricultura Animais, rebanho",II e II,sao_paulo
3,SP_D2_015,SP_D2_015_SPEAKER_1_11_3028.218_3031.298.wav,SPEAKER 1,3.080,e essa máquina costuma ser da própria fazenda ...,D2,1971,M e M,Ótima,"Vegetais, agricultura Animais, rebanho",II e II,sao_paulo
4,SP_D2_015,SP_D2_015_SPEAKER_1_15_3562.448_3566.068.wav,SPEAKER 1,3.620,"tipo moca, isso tem algum... não, moca não não...",D2,1971,M e M,Ótima,"Vegetais, agricultura Animais, rebanho",II e II,sao_paulo

In [24]:
df['inquiry'] = df['inquiry'].str.replace('NURC_', '', regex=False)

In [26]:
inquiry_list = ["SP_DID_052", "SP_DID_065", "SP_DID_102", "SP_DID_110", "SP_DID_014", "SP_DID_023", "SP_DID_027", "SP_DID_031", "RE_DID_001", "RE_DID_013", "RE_DID_025", "RE_DID_037", "RE_DID_045", "RE_DID_044", "RE_DID_032", "RE_DID_058"]

sub_df = df[df['inquiry'].isin(inquiry_list)]

print(f"Number of rows in sub_df: {len(sub_df)}")
display(sub_df.head())

Number of rows in sub_df: 6413

,inquiry,segment,speaker,duration,text,inq_type,inq_recording_year,inq_gender,inq_quality,inq_themes,inq_age_group,split
44792,SP_DID_014,SP_DID_014_SPEAKER_0_0_68.541_72.242.wav,SPEAKER 0,3.701,"doutor , nós queríamos que o senhor nos contas...",DID,1971,M,Ótima,"Alimentação Cidade, comércio Transportes e v...",II,sao_paulo
44793,SP_DID_014,SP_DID_014_SPEAKER_0_1_72.242_77.144.wav,SPEAKER 0,4.902,"em primeiro lugar, como é que o senhor costuma...",DID,1971,M,Ótima,"Alimentação Cidade, comércio Transportes e v...",II,sao_paulo
44794,SP_DID_014,SP_DID_014_SPEAKER_0_2_77.144_85.527.wav,SPEAKER 0,8.383,"a viagem a altamira, inicialmente temos que to...",DID,1971,M,Ótima,"Alimentação Cidade, comércio Transportes e v...",II,sao_paulo
44795,SP_DID_014,SP_DID_014_SPEAKER_0_4_91.45_97.952.wav,SPEAKER 0,6.502,"à noite. de são paulo, entre nove e dez horas ...",DID,1971,M,Ótima,"Alimentação Cidade, comércio Transportes e v...",II,sao_paulo
44796,SP_DID_014,SP_DID_014_SPEAKER_0_5_98.7_116.475.wav,SPEAKER 0,17.775,com escala no rio para um voo depois direto da...,DID,1971,M,Ótima,"Alimentação Cidade, comércio Transportes e v...",II,sao_paulo

In [27]:
columns_to_keep = ['inquiry', 'segment', 'speaker', 'text']
sub_df = sub_df[columns_to_keep]
print("Sub-dataframe with selected columns:")
display(sub_df.head())

Sub-dataframe with selected columns:

,inquiry,segment,speaker,text
44792,SP_DID_014,SP_DID_014_SPEAKER_0_0_68.541_72.242.wav,SPEAKER 0,"doutor , nós queríamos que o senhor nos contas..."
44793,SP_DID_014,SP_DID_014_SPEAKER_0_1_72.242_77.144.wav,SPEAKER 0,"em primeiro lugar, como é que o senhor costuma..."
44794,SP_DID_014,SP_DID_014_SPEAKER_0_2_77.144_85.527.wav,SPEAKER 0,"a viagem a altamira, inicialmente temos que to..."
44795,SP_DID_014,SP_DID_014_SPEAKER_0_4_91.45_97.952.wav,SPEAKER 0,"à noite. de são paulo, entre nove e dez horas ..."
44796,SP_DID_014,SP_DID_014_SPEAKER_0_5_98.7_116.475.wav,SPEAKER 0,com escala no rio para um voo depois direto da...

In [28]:
output_filename = 'nurc_test_16.csv'
sub_df.to_csv(output_filename, index=False)
print(f"sub_df successfully saved to {output_filename}")

sub_df successfully saved to nurc_test_16.csv